# Stage 1: Build the app
FROM node:16-alpine AS builder

# Set working directory
WORKDIR /app

COPY package.json .
RUN npm install
COPY . .

# Stage 2: Use a minimal runtime image
FROM node:16-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3000
CMD ["node", "index.js"]
