# stage 1
FROM python:3.10-slim As builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

# stage 2 
FROM python:3.10-alpine
WORKDIR /app
COPY --from=builder /app .
CMD ["python", "app.py"]
